//Vitor Kenji Soares Yasuda

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Kenji
 */
public class JanelaConsulta extends javax.swing.JFrame {

    private static JanelaConsulta janelaConsulta;

    public static JanelaConsulta getJanelaConsulta() {
        if (janelaConsulta == null) {
            janelaConsulta = new JanelaConsulta();
        }
        return janelaConsulta;
    }

    private Integer idConsulta;

    /**
     * Creates new form JanelaAltDel
     */
    private JanelaConsulta() {
        initComponents();
        btAlterar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCad = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtRaca = new javax.swing.JLabel();
        cxRaca = new javax.swing.JComboBox<>();
        txtPeso = new javax.swing.JLabel();
        txtIdade = new javax.swing.JLabel();
        txtSexo = new javax.swing.JLabel();
        txtCor = new javax.swing.JLabel();
        cxSexo = new javax.swing.JComboBox<>();
        cxPeso = new javax.swing.JTextField();
        cxIdade = new javax.swing.JTextField();
        cxCor = new javax.swing.JTextField();
        txtCor1 = new javax.swing.JLabel();
        txtVacina = new javax.swing.JLabel();
        cxVacina = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JLabel();
        cxQuantidade = new javax.swing.JComboBox<>();
        txtData = new javax.swing.JLabel();
        cxData = new javax.swing.JFormattedTextField();
        txtEspc = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPrimAtrib = new javax.swing.JLabel();
        cxPrimAtrib = new javax.swing.JTextField(){
            @Override
            public String getText() {
                Document doc = getDocument();
                String txt;
                try {
                    txt = doc.getText(0, doc.getLength());
                    if(txt.isEmpty() || txt.matches("[a-zA-Z]+")){
                        txt = "0";
                    }
                } catch (BadLocationException e) {
                    txt = null;
                }
                return txt;
            }
        }
        ;
        txtSegAtrib = new javax.swing.JLabel();
        cxSegAtrib = new javax.swing.JTextField();
        txtTerAtrib = new javax.swing.JLabel();
        cxTerAtrib = new javax.swing.JTextField();
        btAlterar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btLimpar1 = new javax.swing.JButton();
        txtCod = new javax.swing.JLabel();
        cxCod = new javax.swing.JTextField(){
            @Override
            public String getText() {
                Document doc = getDocument();
                String txt;
                try {
                    txt = doc.getText(0, doc.getLength());
                    if(txt.isEmpty() || txt.matches("[a-zA-Z]+")){
                        txt = "-1";
                    }
                } catch (BadLocationException e) {
                    txt = null;
                }
                return txt;
            }
        };
        btCons = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(514, 732));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        txtCad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCad.setText("Ficha");

        txtRaca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRaca.setText("Raça:");

        cxRaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Angus", "Tabapuã", "Nelore" }));
        cxRaca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cxRacaItemStateChanged(evt);
            }
        });
        cxRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxRacaActionPerformed(evt);
            }
        });

        txtPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPeso.setText("Peso:");

        txtIdade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdade.setText("Idade:");

        txtSexo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSexo.setText("Sexo:");

        txtCor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCor.setText("Cor:");

        cxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Macho", "Femêa" }));
        cxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxSexoActionPerformed(evt);
            }
        });

        cxIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxIdadeActionPerformed(evt);
            }
        });

        txtCor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtVacina.setText("Vacina:");

        txtQuantidade.setText("Quantidade:");

        cxQuantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        txtData.setText("Data Compra:");

        txtEspc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtEspc.setText("Especifidade da Raça");

        txtPrimAtrib.setText("Porcentagem Gordural");

        cxPrimAtrib.setToolTipText("");

        txtSegAtrib.setText("Qualidade Carne");

        cxSegAtrib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxSegAtribActionPerformed(evt);
            }
        });

        txtTerAtrib.setText("Precocidade");

        btAlterar.setText("Alterar");
        btAlterar.setToolTipText("");
        btAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btDeletar.setText("Deletar");
        btDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        btLimpar1.setText("Limpar");
        btLimpar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpar1ActionPerformed(evt);
            }
        });

        txtCod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCod.setText("Cod.:");

        cxCod.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btCons.setText("Buscar");
        btCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btLimpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCor1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtSexo)
                        .addGap(12, 12, 12)
                        .addComponent(cxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtCor)
                        .addGap(18, 18, 18)
                        .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtVacina)
                        .addGap(6, 6, 6)
                        .addComponent(cxVacina, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtQuantidade)
                        .addGap(21, 21, 21)
                        .addComponent(cxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(txtEspc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSegAtrib)
                            .addComponent(cxPrimAtrib, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtIdade)
                        .addGap(6, 6, 6)
                        .addComponent(cxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtData)
                        .addGap(13, 13, 13)
                        .addComponent(cxData, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCad)
                .addGap(212, 212, 212))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(txtPrimAtrib))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cxTerAtrib, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTerAtrib, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxSegAtrib, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtPeso)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCod)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxCod))
                .addGap(13, 13, 13)
                .addComponent(btCons)
                .addGap(18, 18, 18)
                .addComponent(txtRaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cxRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtCor1)
                .addGap(7, 7, 7)
                .addComponent(txtCad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCod)
                    .addComponent(cxCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRaca)
                    .addComponent(btCons))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPeso)
                    .addComponent(cxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdade)
                    .addComponent(cxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtData))
                    .addComponent(cxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSexo)
                    .addComponent(cxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCor)
                    .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxVacina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVacina)
                            .addComponent(txtQuantidade))))
                .addGap(17, 17, 17)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtEspc)
                .addGap(12, 12, 12)
                .addComponent(txtPrimAtrib)
                .addGap(6, 6, 6)
                .addComponent(cxPrimAtrib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSegAtrib)
                .addGap(12, 12, 12)
                .addComponent(cxSegAtrib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTerAtrib)
                .addGap(6, 6, 6)
                .addComponent(cxTerAtrib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        setSize(new java.awt.Dimension(497, 726));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cxRacaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cxRacaItemStateChanged
        verificaSetGado((String) cxRaca.getSelectedItem());

    }//GEN-LAST:event_cxRacaItemStateChanged

    private void cxRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxRacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxRacaActionPerformed

    private void cxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxSexoActionPerformed

    private void cxIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxIdadeActionPerformed

    private void cxSegAtribActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxSegAtribActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxSegAtribActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterarGado();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        deletarGado();
    }//GEN-LAST:event_btDeletarActionPerformed

    private void btLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpar1ActionPerformed
        limpar();
    }//GEN-LAST:event_btLimpar1ActionPerformed

    private void btConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsActionPerformed
        consGado();
    }//GEN-LAST:event_btConsActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        JanelaPrincipal.getJanelaPrincipal().listarTab();
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        limpar();
    }//GEN-LAST:event_formWindowClosed

    public void verificaSetGado(String s) {

        switch (s) {
            case "Angus":
                txtPrimAtrib.setText("Porcentagem Gordural");
                txtPrimAtrib.setVisible(true);
                cxPrimAtrib.setVisible(true);

                txtSegAtrib.setText("Qualidade Carne");
                txtSegAtrib.setVisible(true);
                cxSegAtrib.setVisible(true);

                txtTerAtrib.setText("Preocidade");
                txtTerAtrib.setVisible(true);
                cxTerAtrib.setVisible(true);
                break;

            case "Tabapuã":
                txtPrimAtrib.setText("Quantidade Criacao");
                txtPrimAtrib.setVisible(true);
                cxPrimAtrib.setVisible(true);

                txtSegAtrib.setText("Habilidade Materna");
                txtSegAtrib.setVisible(true);
                cxSegAtrib.setVisible(true);

                txtTerAtrib.setText("Fertilidade");
                txtTerAtrib.setVisible(true);
                cxTerAtrib.setVisible(true);
                break;

            case "Nelore":
                txtPrimAtrib.setText("Ganho de Peso");
                txtPrimAtrib.setVisible(true);
                cxPrimAtrib.setVisible(true);

                txtSegAtrib.setText("Nivel de Adaptacao");
                txtSegAtrib.setVisible(true);
                cxSegAtrib.setVisible(true);

                txtTerAtrib.setText("Rusticidade");
                txtTerAtrib.setVisible(true);
                cxTerAtrib.setVisible(true);
                break;

            case "Selecione":
                txtPrimAtrib.setVisible(false);
                cxPrimAtrib.setVisible(false);
                txtSegAtrib.setVisible(false);
                cxSegAtrib.setVisible(false);
                txtTerAtrib.setVisible(false);
                cxTerAtrib.setVisible(false);
                break;
        }

    }

    public void mensagemTela(boolean condicao, String msg) {
        if (condicao) {
            JOptionPane.showMessageDialog(this, msg, "Aviso", 1);
        } else {
            JOptionPane.showMessageDialog(this, msg, "Erro", 0);

        }

    }

    public void alterarGado() {
        if (cxCod.getText().isEmpty()) {
            mensagemTela(false, "Insira o codigo");
            cxCod.requestFocus();
            return;
        }
        Gado gado = null;
        switch ((String) cxRaca.getSelectedItem()) {
            case "Angus":
                gado = getAngus();
                if (gado != null) {
                    gado.setCodigo(Integer.parseInt(cxCod.getText()));
                    BDGado.getBanco().altGado((Angus) gado);
                    mensagemTela(true, "Gado alterado");
                    limpar();
                }
                
                return;

            case "Tabapuã":
                gado = getTabapua();
                gado.setCodigo(Integer.parseInt(cxCod.getText()));
                if (gado != null) {
                    BDGado.getBanco().altGado((Tabapua) gado);
                    mensagemTela(true, "Gado alterado");
                    limpar();
                }
                return;

            case "Nelore":
                gado = getNelore();
                gado.setCodigo(Integer.parseInt(cxCod.getText()));
                if (gado != null) {
                    BDGado.getBanco().altGado((Nelore) gado);
                    mensagemTela(true, "Gado alterado");
                    limpar();
                }
                return;

            case "Selecione":
                JOptionPane.showInputDialog(this, "A raça deve ser selecionada!", 0);
                return;
        }
        
    }

    public void deletarGado() {
        if (cxCod.getText().isEmpty()) {
            mensagemTela(false, "Insira o codigo");
            cxCod.requestFocus();
            return;
        }
        try {
            if (BDGado.getBanco().deletarGado(Integer.parseInt(cxCod.getText()))) {
                mensagemTela(true, "Deletado com sucesso");
                limpar();
            }

        } catch (NumberFormatException nfe) {
            mensagemTela(false, "O codigo deve ser um numero");
            cxCod.requestFocus();

        }

    }

    public void consGado() {
        Gado gado = BDGado.getBanco().buscarPorCod(Integer.parseInt(cxCod.getText()));
        if (gado == null) {
            mensagemTela(false, "Gado nao encontrado");
            return;
        }
        if (gado.getRaca().equals("Angus")) {
            setAngus((Angus) gado);
        } else if (gado.getRaca().contains("Nelore")) {
            setNelore((Nelore) gado);
        } else {
            setTabapua((Tabapua) gado);
        }
        mensagemTela(true, "Gado encontrado");
        btAlterar.setVisible(true);

    }

    public Nelore getNelore() {
        try{
        Nelore nelore = new Nelore();
        nelore.setRaca((String) cxRaca.getSelectedItem());
        nelore.setPeso(Float.parseFloat(cxPeso.getText()));
        nelore.setIdade(Integer.parseInt(cxIdade.getText()));
        nelore.setSexo((String) cxSexo.getSelectedItem());
        try {
            DateTimeFormatter formatar = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate date = LocalDate.parse(cxData.getText(), formatar);
            nelore.setDataCompra(date);

        } catch (Exception formatar) {
            JOptionPane.showMessageDialog(this, "O formato deve ser: dd/mm/aaaa", "Erro", 0);
            return null;
        }
        nelore.setCor(cxCor.getText());
        nelore.getHistorico().setVacina(cxVacina.getText());
        nelore.getHistorico().setQuantVacina(Integer.parseInt((String) cxQuantidade.getSelectedItem()));
        nelore.setGanhoPeso(Integer.parseInt(cxPrimAtrib.getText()));
        nelore.setNivelAdapt(cxSegAtrib.getText());
        nelore.setRusticidade(cxTerAtrib.getText());
        return nelore;
        }catch(NumberFormatException nfe){
            mensagemTela(false,"Idade e peso devem ser um numero!");
            return null;
        }
    }

    public Angus getAngus() {
        try{
        Angus angus = new Angus();
        angus.setRaca((String) cxRaca.getSelectedItem());
        angus.setPeso(Float.parseFloat(cxPeso.getText()));
        angus.setIdade(Integer.parseInt(cxIdade.getText()));
        angus.setSexo((String) cxSexo.getSelectedItem());
        try {
            DateTimeFormatter formatar = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate date = LocalDate.parse(cxData.getText(), formatar);
            angus.setDataCompra(date);

        } catch (Exception formatar) {
            JOptionPane.showMessageDialog(this, "O formato deve ser: dd/mm/aaaa", "Erro", 0);
            return null;
        }
        angus.setCor(cxCor.getText());
        angus.getHistorico().setVacina(cxVacina.getText());
        angus.getHistorico().setQuantVacina(Integer.parseInt((String) cxQuantidade.getSelectedItem()));
        angus.setQuantGordura(Integer.parseInt(cxPrimAtrib.getText()));
        angus.setQualCarne(cxSegAtrib.getText());
        angus.setPrecocidade(cxTerAtrib.getText());
        return angus;
        }catch(NumberFormatException nfe){
            mensagemTela(false,"Idade e peso devem ser um numero!");
            return null;
        }
    }

    public Tabapua getTabapua() {
        try{
        Tabapua tabapua = new Tabapua();
        tabapua.setRaca((String) cxRaca.getSelectedItem());
        tabapua.setPeso(Float.parseFloat(cxPeso.getText()));
        tabapua.setIdade(Integer.parseInt(cxIdade.getText()));
        tabapua.setSexo((String) cxSexo.getSelectedItem());
        try {
            DateTimeFormatter formatar = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate date = LocalDate.parse(cxData.getText(), formatar);
            tabapua.setDataCompra(date);

        } catch (Exception formatar) {
            JOptionPane.showMessageDialog(this, "O formato deve ser: dd/mm/aaaa", "Erro", 0);
            return null;
        }
        tabapua.setCor(cxCor.getText());
        tabapua.getHistorico().setVacina(cxVacina.getText());
        tabapua.getHistorico().setQuantVacina(Integer.parseInt((String) cxQuantidade.getSelectedItem()));
        tabapua.setQuantCria(Integer.parseInt(cxPrimAtrib.getText()));
        tabapua.setHabMaterna(cxSegAtrib.getText());
        tabapua.setFertilidade(cxTerAtrib.getText());
        return tabapua;
        }catch(NumberFormatException nfe){
            mensagemTela(false,"Idade e peso devem ser um numero!");
            return null;
        }
    }

    public void setNelore(Nelore nelore) {

        cxCor.setText(nelore.getCor());
        cxIdade.setText(nelore.getIdade().toString());
        cxPeso.setText(nelore.getPeso().toString());
        DateTimeFormatter formatar = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        cxData.setText(nelore.getDataCompra().format(formatar));
        cxVacina.setText(nelore.getHistorico().getVacina());
        cxRaca.setSelectedIndex(3);
        cxSexo.setSelectedItem(nelore.getSexo());
        cxQuantidade.setSelectedItem(nelore.getHistorico().getquantVacina());
        cxPrimAtrib.setText(String.valueOf(nelore.getGanhoPeso()));
        cxSegAtrib.setText(nelore.getNivelAdapt());
        cxTerAtrib.setText(nelore.getRusticidade());
        verificaSetGado("Nelore");

    }

    public void setAngus(Angus angus) {

        cxCor.setText(angus.getCor());
        cxIdade.setText(angus.getIdade().toString());
        cxPeso.setText(angus.getPeso().toString());
        DateTimeFormatter formatar = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        cxData.setText(angus.getDataCompra().format(formatar));
        cxVacina.setText(angus.getHistorico().getVacina());
        cxRaca.setSelectedIndex(1);
        cxSexo.setSelectedItem(angus.getSexo());
        cxQuantidade.setSelectedItem(angus.getHistorico().getquantVacina());
        cxPrimAtrib.setText(String.valueOf(angus.getQuantGordura()));
        cxSegAtrib.setText(angus.getQualCarne());
        cxTerAtrib.setText(angus.getPrecocidade());
        verificaSetGado("Angus");
    }

    public void setTabapua(Tabapua tabapua) {

        cxCor.setText(tabapua.getCor());
        cxIdade.setText(tabapua.getIdade().toString());
        cxPeso.setText(tabapua.getPeso().toString());
        DateTimeFormatter formatar = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        cxData.setText(tabapua.getDataCompra().format(formatar));
        cxVacina.setText(tabapua.getHistorico().getVacina());
        cxRaca.setSelectedIndex(2);
        cxSexo.setSelectedItem(tabapua.getSexo());
        cxQuantidade.setSelectedItem(tabapua.getHistorico().getquantVacina());
        cxPrimAtrib.setText(String.valueOf(tabapua.getQuantCria()));
        cxSegAtrib.setText(tabapua.getHabMaterna());
        cxTerAtrib.setText(tabapua.getFertilidade());
        verificaSetGado("Tabapua");
    }

    public void limpar() {
        cxCod.setText("");
        cxCor.setText("");
        cxIdade.setText("");
        cxPeso.setText("");
        cxData.setText("");
        cxVacina.setText("");
        cxRaca.setSelectedIndex(0);
        cxSexo.setSelectedIndex(0);
        cxQuantidade.setSelectedIndex(0);
        btAlterar.setVisible(false);
        cxRacaItemStateChanged(null);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCons;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btLimpar1;
    private javax.swing.JTextField cxCod;
    private javax.swing.JTextField cxCor;
    private javax.swing.JFormattedTextField cxData;
    private javax.swing.JTextField cxIdade;
    private javax.swing.JTextField cxPeso;
    private javax.swing.JTextField cxPrimAtrib;
    private javax.swing.JComboBox<String> cxQuantidade;
    private javax.swing.JComboBox<String> cxRaca;
    private javax.swing.JTextField cxSegAtrib;
    private javax.swing.JComboBox<String> cxSexo;
    private javax.swing.JTextField cxTerAtrib;
    private javax.swing.JTextField cxVacina;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel txtCad;
    private javax.swing.JLabel txtCod;
    private javax.swing.JLabel txtCor;
    private javax.swing.JLabel txtCor1;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtEspc;
    private javax.swing.JLabel txtIdade;
    private javax.swing.JLabel txtPeso;
    private javax.swing.JLabel txtPrimAtrib;
    private javax.swing.JLabel txtQuantidade;
    private javax.swing.JLabel txtRaca;
    private javax.swing.JLabel txtSegAtrib;
    private javax.swing.JLabel txtSexo;
    private javax.swing.JLabel txtTerAtrib;
    private javax.swing.JLabel txtVacina;
    // End of variables declaration//GEN-END:variables
}
