//Vitor Kenji Soares Yasuda

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Kenji
 */
public class JanelaCadastro extends javax.swing.JFrame {

    private static JanelaCadastro janelaCadastro;

    public static JanelaCadastro getJanelaCadastro() {
        if (janelaCadastro == null) {
            janelaCadastro = new JanelaCadastro();

        }
        return janelaCadastro;
    }

    private JanelaCadastro() {
        initComponents();
        limpar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCad = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtRaca = new javax.swing.JLabel();
        cxRaca = new javax.swing.JComboBox<>();
        txtPeso = new javax.swing.JLabel();
        txtIdade = new javax.swing.JLabel();
        txtSexo = new javax.swing.JLabel();
        txtCor = new javax.swing.JLabel();
        cxSexo = new javax.swing.JComboBox<>();
        cxPeso = new javax.swing.JTextField();
        cxIdade = new javax.swing.JTextField();
        cxCor = new javax.swing.JTextField();
        txtCor1 = new javax.swing.JLabel();
        txtVacina = new javax.swing.JLabel();
        cxVacina = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JLabel();
        cxQuantidade = new javax.swing.JComboBox<>();
        txtData = new javax.swing.JLabel();
        cxData = new javax.swing.JFormattedTextField();
        txtEspc = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPrimAtrib = new javax.swing.JLabel();
        cxPrimAtrib = new javax.swing.JTextField();
        txtSegAtrib = new javax.swing.JLabel();
        cxSegAtrib = new javax.swing.JTextField();
        txtTerAtrib = new javax.swing.JLabel();
        cxTerAtrib = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        txtCad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCad.setText("Cadastro");

        txtRaca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRaca.setText("Raça:");

        cxRaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Angus", "Tabapuã", "Nelore" }));
        cxRaca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cxRacaItemStateChanged(evt);
            }
        });
        cxRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxRacaActionPerformed(evt);
            }
        });

        txtPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPeso.setText("Peso:");

        txtIdade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdade.setText("Idade:");

        txtSexo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSexo.setText("Sexo:");

        txtCor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCor.setText("Cor:");

        cxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Macho", "Femêa" }));
        cxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxSexoActionPerformed(evt);
            }
        });

        cxIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxIdadeActionPerformed(evt);
            }
        });

        txtCor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtVacina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtVacina.setText("Vacina:");

        txtQuantidade.setText("Quantidade:");

        cxQuantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        txtData.setText("Data Compra:");

        txtEspc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtEspc.setText("Especifidade da Raça");

        txtPrimAtrib.setText("Porcentagem Gordural");

        txtSegAtrib.setText("Qualidade Carne");

        cxSegAtrib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxSegAtribActionPerformed(evt);
            }
        });

        txtTerAtrib.setText("Precocidade");

        btCadastrar.setText("Cadastrar");
        btCadastrar.setToolTipText("Cadastro volátil");
        btCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCor1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(txtCad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtRaca)
                        .addGap(12, 12, 12)
                        .addComponent(cxRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtPeso)
                        .addGap(11, 11, 11)
                        .addComponent(cxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtIdade)
                        .addGap(6, 6, 6)
                        .addComponent(cxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtData)
                        .addGap(13, 13, 13)
                        .addComponent(cxData, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtSexo)
                        .addGap(12, 12, 12)
                        .addComponent(cxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtCor)
                        .addGap(18, 18, 18)
                        .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtVacina)
                        .addGap(6, 6, 6)
                        .addComponent(cxVacina, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtQuantidade)
                        .addGap(21, 21, 21)
                        .addComponent(cxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(txtEspc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(txtPrimAtrib))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(cxPrimAtrib, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(txtSegAtrib))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(cxSegAtrib, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(txtTerAtrib))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(cxTerAtrib, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 143, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtCor1)
                .addGap(13, 13, 13)
                .addComponent(txtCad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRaca)
                    .addComponent(cxRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPeso)
                    .addComponent(cxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdade)
                    .addComponent(cxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtData))
                    .addComponent(cxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSexo)
                    .addComponent(cxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCor)
                    .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxVacina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVacina)
                            .addComponent(txtQuantidade))))
                .addGap(17, 17, 17)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtEspc)
                .addGap(12, 12, 12)
                .addComponent(txtPrimAtrib)
                .addGap(6, 6, 6)
                .addComponent(cxPrimAtrib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSegAtrib)
                .addGap(6, 6, 6)
                .addComponent(cxSegAtrib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTerAtrib)
                .addGap(6, 6, 6)
                .addComponent(cxTerAtrib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        setSize(new java.awt.Dimension(530, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cxIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxIdadeActionPerformed

    private void cxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxSexoActionPerformed

    private void cxRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxRacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxRacaActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void cxSegAtribActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxSegAtribActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxSegAtribActionPerformed

    private void cxRacaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cxRacaItemStateChanged
        switch ((String) cxRaca.getSelectedItem()) {

            case "Angus":
                txtPrimAtrib.setText("Porcentagem Gordural");
                txtPrimAtrib.setVisible(true);
                cxPrimAtrib.setVisible(true);

                txtSegAtrib.setText("Qualidade Carne");
                txtSegAtrib.setVisible(true);
                cxSegAtrib.setVisible(true);

                txtTerAtrib.setText("Preocidade");
                txtTerAtrib.setVisible(true);
                cxTerAtrib.setVisible(true);
                break;

            case "Tabapuã":
                txtPrimAtrib.setText("Quantidade Criacao");
                txtPrimAtrib.setVisible(true);
                cxPrimAtrib.setVisible(true);

                txtSegAtrib.setText("Habilidade Materna");
                txtSegAtrib.setVisible(true);
                cxSegAtrib.setVisible(true);

                txtTerAtrib.setText("Fertilidade");
                txtTerAtrib.setVisible(true);
                cxTerAtrib.setVisible(true);
                break;

            case "Nelore":
                txtPrimAtrib.setText("Ganho de Peso");
                txtPrimAtrib.setVisible(true);
                cxPrimAtrib.setVisible(true);

                txtSegAtrib.setText("Nivel de Adaptacao");
                txtSegAtrib.setVisible(true);
                cxSegAtrib.setVisible(true);

                txtTerAtrib.setText("Rusticidade");
                txtTerAtrib.setVisible(true);
                cxTerAtrib.setVisible(true);
                break;

            case "Selecione":
                txtPrimAtrib.setVisible(false);
                cxPrimAtrib.setVisible(false);
                txtSegAtrib.setVisible(false);
                cxSegAtrib.setVisible(false);
                txtTerAtrib.setVisible(false);
                cxTerAtrib.setVisible(false);
                break;
        }
    }//GEN-LAST:event_cxRacaItemStateChanged

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadGado();

    }//GEN-LAST:event_btCadastrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated

    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        limpar();
        JanelaPrincipal.getJanelaPrincipal().listarTab();
    }//GEN-LAST:event_formWindowClosed

    public void cadGado() {
        Gado gado = null;
        switch ((String) cxRaca.getSelectedItem()) {
            case "Angus":
                gado = getAngus();
                if (gado != null) {
                    BDGado.getBanco().cadGado((Angus) gado);
                }
                break;

            case "Tabapuã":
                gado = getTabapua();
                if (gado != null) {
                    BDGado.getBanco().cadGado((Tabapua) gado);
                }
                break;

            case "Nelore":
                gado = getNelore();
                if (gado != null) {
                    BDGado.getBanco().cadGado((Nelore) gado);
                }
                break;

            case "Selecione":
                mensagemTela(true, "A raça deve ser selecionada!");

                break;
        }
        if (gado != null) {
            mensagemTela(true, "Cadastrado com sucesso");
            this.dispose();
        }
    }

    public void mensagemTela(boolean condicao, String msg) {
        if (condicao) {
            JOptionPane.showMessageDialog(this, msg, "Aviso", 1);
        } else {
            JOptionPane.showMessageDialog(this, msg, "Erro", 0);

        }

    }

    public Nelore getNelore() {
        try {
            Nelore nelore = new Nelore();
            nelore.setRaca((String) cxRaca.getSelectedItem());
            nelore.setPeso(Float.parseFloat(cxPeso.getText()));
            nelore.setIdade(Integer.parseInt(cxIdade.getText()));
            nelore.setSexo((String) cxSexo.getSelectedItem());
            try {
                DateTimeFormatter formatar = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                LocalDate date = LocalDate.parse(cxData.getText(), formatar);
                nelore.setDataCompra(date);

            } catch (Exception formatar) {
                JOptionPane.showMessageDialog(this, "O formato deve ser: dd/mm/aaaa", "Erro", 0);
                return null;
            }
            nelore.setCor(cxCor.getText());
            nelore.getHistorico().setVacina(cxVacina.getText());
            nelore.getHistorico().setQuantVacina(Integer.parseInt((String) cxQuantidade.getSelectedItem()));
            nelore.setGanhoPeso(Integer.parseInt(cxPrimAtrib.getText()));
            nelore.setNivelAdapt(cxSegAtrib.getText());
            nelore.setRusticidade(cxTerAtrib.getText());
            return nelore;
        } catch (NumberFormatException nfe) {
            mensagemTela(false, "Idade e peso devem ser um numero!");
            return null;
        }
    }

    public Angus getAngus() {
        try {
            Angus angus = new Angus();
            angus.setRaca((String) cxRaca.getSelectedItem());
            angus.setPeso(Float.parseFloat(cxPeso.getText()));
            angus.setIdade(Integer.parseInt(cxIdade.getText()));
            angus.setSexo((String) cxSexo.getSelectedItem());
            try {
                DateTimeFormatter formatar = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                LocalDate date = LocalDate.parse(cxData.getText(), formatar);
                angus.setDataCompra(date);

            } catch (Exception formatar) {
                JOptionPane.showMessageDialog(this, "O formato deve ser: dd/mm/aaaa", "Erro", 0);
                return null;
            }
            angus.setCor(cxCor.getText());
            angus.getHistorico().setVacina(cxVacina.getText());
            angus.getHistorico().setQuantVacina(Integer.parseInt((String) cxQuantidade.getSelectedItem()));
            angus.setQuantGordura(Integer.parseInt(cxPrimAtrib.getText()));
            angus.setQualCarne(cxSegAtrib.getText());
            angus.setPrecocidade(cxTerAtrib.getText());
            return angus;

        } catch (NumberFormatException nfe) {
            mensagemTela(false, "Idade e peso devem ser um numero!");
            return null;
        }
    }

    public Tabapua getTabapua() {
        try{
        Tabapua tabapua = new Tabapua();
        tabapua.setRaca((String) cxRaca.getSelectedItem());
        tabapua.setPeso(Float.parseFloat(cxPeso.getText()));
        tabapua.setIdade(Integer.parseInt(cxIdade.getText()));
        tabapua.setSexo((String) cxSexo.getSelectedItem());
        try {
            DateTimeFormatter formatar = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate date = LocalDate.parse(cxData.getText(), formatar);
            tabapua.setDataCompra(date);

        } catch (Exception formatar) {
            JOptionPane.showMessageDialog(this, "O formato deve ser: dd/mm/aaaa", "Erro", 0);
            return null;
        }
        tabapua.setCor(cxCor.getText());
        tabapua.getHistorico().setVacina(cxVacina.getText());
        tabapua.getHistorico().setQuantVacina(Integer.parseInt((String) cxQuantidade.getSelectedItem()));
        tabapua.setQuantCria(Integer.parseInt(cxPrimAtrib.getText()));
        tabapua.setHabMaterna(cxSegAtrib.getText());
        tabapua.setFertilidade(cxTerAtrib.getText());
        return tabapua;
        }catch(NumberFormatException nfe){
            mensagemTela(false,"Idade e peso devem ser um numero!");
            return null;
        }
    }
        

    public void limpar() {
        cxCor.setText("");
        cxIdade.setText("");
        cxPeso.setText("");
        cxData.setText("");
        cxVacina.setText("");
        cxRaca.setSelectedIndex(0);
        cxSexo.setSelectedIndex(0);
        cxQuantidade.setSelectedIndex(0);
        cxPrimAtrib.setText("");
        cxSegAtrib.setText("");
        cxTerAtrib.setText("");
        txtPrimAtrib.setVisible(false);
        cxPrimAtrib.setVisible(false);
        txtSegAtrib.setVisible(false);
        cxSegAtrib.setVisible(false);
        txtTerAtrib.setVisible(false);
        cxTerAtrib.setVisible(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JTextField cxCor;
    private javax.swing.JFormattedTextField cxData;
    private javax.swing.JTextField cxIdade;
    private javax.swing.JTextField cxPeso;
    private javax.swing.JTextField cxPrimAtrib;
    private javax.swing.JComboBox<String> cxQuantidade;
    private javax.swing.JComboBox<String> cxRaca;
    private javax.swing.JTextField cxSegAtrib;
    private javax.swing.JComboBox<String> cxSexo;
    private javax.swing.JTextField cxTerAtrib;
    private javax.swing.JTextField cxVacina;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel txtCad;
    private javax.swing.JLabel txtCor;
    private javax.swing.JLabel txtCor1;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtEspc;
    private javax.swing.JLabel txtIdade;
    private javax.swing.JLabel txtPeso;
    private javax.swing.JLabel txtPrimAtrib;
    private javax.swing.JLabel txtQuantidade;
    private javax.swing.JLabel txtRaca;
    private javax.swing.JLabel txtSegAtrib;
    private javax.swing.JLabel txtSexo;
    private javax.swing.JLabel txtTerAtrib;
    private javax.swing.JLabel txtVacina;
    // End of variables declaration//GEN-END:variables
}
